name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Enable Cloud Functions API
      run: |
        gcloud services enable cloudfunctions.googleapis.com

    - name: Enable Cloud Build API
      run: |
        gcloud services enable cloudbuild.googleapis.com

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy helloWorld \
          --runtime nodejs14 \
          --trigger-http \
          --allow-unauthenticated
